### ISSUE TITLE
bash.bashrc

### ISSUE THREAD

**Issue by JyanJohn** [Mrp1r4t3/Parrot-in-Termux2#1]
Is there a way to change 

┌─[u0_a1306@localhost]─[~]
└──╼ $

To

┌─[jyanjohn@sadmachine]─[~]
└──╼ $

by editing the bash.bashrc file?

**Comment by Mrp1r4t3** [comment]
> Is there a way to change
> 
> ┌─[u0_a1306@localhost]─[~] └──╼ $
> 
> To
> 
> ┌─[jyanjohn@sadmachine]─[~] └──╼ $
> 
> by editing the bash.bashrc file?

Here bro: https://pastebin.com/raw/bB1cHyDE

**Comment by Mrp1r4t3** [comment]
> Is there a way to change
> 
> ┌─[u0_a1306@localhost]─[~] └──╼ $
> 
> To
> 
> ┌─[jyanjohn@sadmachine]─[~] └──╼ $
> 
> by editing the bash.bashrc file?

I will update the script soon
